version: "3"
services:
  storage_neo4j:
    image: neo4j:4.1
    environment:
      - NEO4J_AUTH=none # Demo only
    ports: 
      - 7474:7474       # Demo only
      - 7687:7687       # Demo only
  storage_redis:
    image: redis:6
  app:
    container_name: attack_predictor
    build: .
    depends_on:
      - storage_neo4j
      - storage_redis
    environment:
      - NEO4J_URI=bolt://storage_neo4j
      - REDIS_URI=redis://storage_redis
    ports:
      - 5000:5000
